---
- name: "Windows Client | Stop Velociraptor Service"
  ansible.windows.win_service:
    name: Velociraptor
    state: stopped

- name: "Windows Client | Uninstall velociraptor msi"
  ansible.windows.win_package:
    path: "{{ _velociraptor_windows_dir }}{{ velociraptor_msi }}"
    state: absent

- name: "Windows Client | Remove directory"
  ansible.windows.win_file:
    path: "{{ _velociraptor_windows_dir }}"
    state: absent
