rich
psutil
Jinja2
pyyaml
# Ansible
ansible_runner
# ansible-core 2.12.6 min version python 3.8
ansible-core==2.12.6
pywinrm
# AZURE
azure-identity
azure-mgmt-compute
azure-mgmt-network
# AWS
boto3
# Proxmox
proxmoxer
requests