- name: Set CertificateMappingMethods to 0x4 (UPN)
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\SecurityProviders\Schannel
    name: CertificateMappingMethods
    data: 0x4
    type: dword
  vars:
    ansible_become: yes
    ansible_become_method: runas
    domain_name: "{{domain}}"
    ansible_become_user: "{{domain_username}}"
    ansible_become_password: "{{domain_password}}"