boxes.append(
    { :name => "{{lab_name}}-dummy",
      :ip => "{{ip_range}}.169",
      :box => "bento/debian-12",
      :os => "linux",
      :cpus => 1,
      :mem => 1000,
      :forwarded_port => [ {:guest => 22, :host => 22169, :id => "ssh"} ]
    }
)
