boxes.append(
  { :name => "{{lab_name}}-W11-25H2",
    :ip => "{{ip_range}}.35",
    :box => "gusztavvargadr/windows-11-25h2-enterprise",
    :os => "windows",
    :cpus => 2,
    :mem => 4000
  }
)
