boxes.append(
    { :name => "{{lab_name}}-VELOCIRAPTOR",
      :ip => "{{ip_range}}.52",
      :box => "bento/ubuntu-22.04", 
      :os => "linux",
      :distro => "ubuntu",
      :cpus => 2,
      :mem => 4000,
      :forwarded_port => [ {:guest => 22, :host => 2212, :id => "ssh"} ]
    }
)