boxes.append(
  { :name => "{{lab_name}}-NEMESIS",
    :ip => "{{ip_range}}.53",
    :box => "bento/ubuntu-24.04",
    :os => "linux",
    :distro => "ubuntu",
    :cpus => 4,
    :mem => 12000,
    :forwarded_port => [ {:guest => 22, :host => 2213, :id => "ssh"} ]
  }
)
