  - vm_name: "{{ range_id }}-COMMANDO"
    hostname: "{{ range_id }}-COMMANDO"
    template: commando-18FEB26
    vlan: 10
    ip_last_octet: 61
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
      install_additional_tools: true
      chocolatey_packages:
        - wireshark