boxes.append(
  { :name => "{{lab_name}}-W11-23H2",
    :ip => "{{ip_range}}.31",
    :box => "gusztavvargadr/windows-11-23h2-enterprise",
    :os => "windows",
    :cpus => 2,
    :mem => 4000
  }
)
