---
# - name: Clone Rita-ELK Git repository
#   git:
#     repo: 'https://github.com/example/repo.git'
#     dest: '/opt/rita-elk'
#     version: 'main'  # You can specify the branch or tag here
#     update: yes  # Ensures the repo is updated if it already exists

- name: Copy files to destination server
  copy:
    src: "{{ item }}"
    dest: /opt/rita-elk/
    force: true
  loop:
    - "Elasticsearch"
    - "Kibana"
    - "Logstash"
    - "Rita"

- name: Install RITA index template into Elasticsearch
  shell: >
    "curl -X PUT https://{{ es_api_basic_auth_username }}:{{ es_api_basic_auth_password }}@{{ elk_host }}:9200/_template/template-rita -H 'Content-Type: application/json' --data-binary "@/opt/rita-elk/Elasticsearch/template-rita.json" -k"

- name: Import RITA dashboard into Kibana
  shell: >
    "curl -X POST https://{{ es_api_basic_auth_username }}:{{ es_api_basic_auth_password }}@{{ elk_host }}:5601/api/saved_objects/_import?createNewCopies=false --form file='@/opt/rita-elk/Kibana/rita_dashboards.ndjson' -H 'kbn-xsrf: true' -k"

- name: Copy cron file to hourly parse zeek logs
  copy:
    src: /opt/rita-elk/Rita/rita.cron
    dest: /etc/cron.d/
    remote_src: true

- name: Copy logstash configuration files
  copy:
    src: /opt/rita-elk/Logstash/*
    dest: /etc/logstash/conf.d/
    remote_src: true

- name: Replace lines in config file
  lineinfile:
    path: /etc/logstash/conf.d/10-rita_filter.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^(.*)hosts => ["<ip_elasticsearch>:9200"](.*)$', line: 'hosts => ["{{ elk_host }}:9200"]' }
    - { regexp: '^(.*)user => username(.*)$', line: 'user => {{ es_api_basic_auth_username }}' }
    - { regexp: '^(.*)password => password(.*)$', line: 'password => {{ es_api_basic_auth_password }}' }

- name: Restart elasticsearch and kibana
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - elasticsearch
    - kibana