boxes.append(
    { :name => "{{lab_name}}-KALI-OPS",
      :ip => "{{ip_range}}.60",
      :box => "kalilinux/rolling", 
      :distro => "ubuntu",
      :os => "linux",
      :cpus => 2,
      :mem => 8000,
      :forwarded_port => [ {:guest => 22, :host => 2214, :id => "ssh"} ]
    }
)