  - vm_name: "{{ range_id }}-VELOCIRAPTOR"
    hostname: "{{ range_id }}-VELOCIRAPTOR"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 52
    ram_gb: 8
    cpus: 2
    linux: true
